ALTER DATABASE php2 CHARACTER SET utf8 COLLATE utf8_unicode_ci;

create table posts
(
  id int auto_increment
    primary key,
  user_id int null,
  image varchar(255) null,
  content text(1000) CHARACTER SET utf8 not null,
  like_count int default '0' null,
  comment_count int default '0' null,
  created_at timestamp default CURRENT_TIMESTAMP not null,
  updated_at timestamp default CURRENT_TIMESTAMP not null
);

ALTER TABLE posts CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

INSERT INTO posts (user_id, image, content, like_count, comment_count, created_at, updated_at) VALUES (null, 'https://pp.userapi.com/c840222/v840222706/312cb/k4gEEWBz_sI.jpg', 'В эту среду, 18 октября, руководитель нашего агентства <a href="/vvv" class="mem_link" mention="" mention_id="id18658" onclick="return mentionClick(this, event)" onmouseover="mentionOver(this)">Дмитрий Васильев</a> выступит на медиа-конференции Internet &amp; Digital. <br><br>Дмитрий расскажет о влиянии автоматизации бизнес процессов на эффективность коммуникаций с клиентом. <br><br>Сегодня коммуникации с клиентом предполагают большое количество площадок и немалый инструментарий Поэтому перед бизнесом встает вопрос оптимизации процессов и снижения риски в "открытом космосе" коммуникаций. На примере наших кейсов разработки IT-решений для компаний покажем как этого достичь.<br><br>Начало в 10:00, регистрация на сайте: <a href="/away.php?to=http%3A%2F%2Finternetdigital.ru&amp;post=-116542303_66&amp;cc_key=" target="_blank">http://internetdigital.ru</a>', 0, 2, '2018-03-20 01:11:24', '2018-03-20 01:11:24');
INSERT INTO posts (user_id, image, content, like_count, comment_count, created_at, updated_at) VALUES (null, 'https://pp.userapi.com/c837328/v837328450/64558/p3qbyxqbaxg.jpg', 'Решили присоединиться к волне <a href="/feed?section=search&amp;q=%237%D0%B2%D0%B5%D1%89%D0%B5%D0%B9">#7вещей</a> и рассказать, от чего отказались мы в нашем агентстве:<br><br>1. Еще на старте мы отказались от разработки гибридных мобильных приложений. Мы проектируем и создаем нативные приложения под платформы iOS и Android <img class="emoji" src="https://vk.com/images/emoji/D83EDD33D83CDFFB.png"><br><br>2. Code Pilots не берет заказы на создание лендингов. Для нас это задачи, в которых нет возможности применения наших знаний и опыта<img class="emoji" src="https://vk.com/images/emoji/D83DDE45200D2642FE0F.png"><br style="display: none;"><a class="wall_post_more" onclick="hide(this, domPS(this)); show(domNS(this));" style="display: none;">Показать полностью…</a><span style=""><br><br>3. И мы решили, что будем работать над интересными и сложными проектами<img class="emoji"  src="https://vk.com/images/emoji/D83DDC68200DD83DDCBBFE0F.png"><br><br>4. Путем проб и ошибок перестали недооценивать сроки по проектам<img class="emoji" src="https://vk.com/images/emoji/D83DDD25.png"><br><br>5. Мы не работаем по бартеру<img class="emoji" src="https://vk.com/images/emoji/D83DDE45200D2642FE0F.png"><br><br>6. У нас нет графика работы с 9.00 до 18.00 для всех сотрудников, каждый формирует свой<img class="emoji_css" emoji="D83DDC4C" style="background-position: 0px -527px;" src="https://vk.com/images/blank.gif"><br><br>7. И мы отказались от традиции "обед в Макдональдс каждую среду", хоть и не все этому рады :) А в нашем офисе появились тренажеры<img class="emoji" src="https://vk.com/images/emoji/D83CDFC3200D2640FE0F.png"><br><br>А от чего отказались вы?</span>', 7, 1, '2018-03-20 01:12:01', '2018-03-20 01:12:01');
INSERT INTO posts (user_id, image, content, like_count, comment_count, created_at, updated_at) VALUES (null, 'https://pp.userapi.com/c840535/v840535551/167c5/XuoGw1S6lP8.jpg', 'На радость нам вышел новый рейтинг разработчиков мобильных приложений Рунета. Мы продолжаем расти: прибавив 6 пунктов, в этом году мы 13-е по Санкт-Петербургу и 1-е в верхнем ценовом сегменте <a href="/away.php?to=http%3A%2F%2Fwww.ratingruneta.ru%2Fapps%2Fst-petersburg%2F&amp;post=-116542303_60&amp;cc_key=" target="_blank">http://www.ratingruneta.ru/apps/st-petersburg/</a><br><br>По этому случаю расскажем немного о наших достижениях в мобильной разработке. <br><br>В 2017 году мы:<br>- Разработали приложение для VK Fest 2017;<br>- Спроектировали новую версию приложения для <a href="/away.php?to=http%3A%2F%2FPetshop.ru&amp;post=-116542303_60&amp;cc_key=" target="_blank">Petshop.ru</a>; <br>- Разработали приложение для сервиса личных дворецких НеVидимка;<br>- Готовим к запуску мобильное приложение для делового клуба Эталон.', 11, 4, '2018-03-20 01:12:42', '2018-03-20 01:12:42');
INSERT INTO posts (user_id, image, content, like_count, comment_count, created_at, updated_at) VALUES (null, 'https://pp.userapi.com/c837724/v837724974/5cf11/2H-0XQflaOc.jpg', 'Знакомьтесь, это наш UX-специалист <a href="/vyacheslavseredenko" class="mem_link" mention="" mention_id="id23976707" onclick="return mentionClick(this, event)" onmouseover="mentionOver(this)">Слава Середенко</a> в деле. Он любит людей и цифры. Пытается понять первых и объяснить их поведение при помощи вторых.<br><br>Именно этот подход он применяет в работе над новой CRM-системой для проекта Персональные решения.', 15, 0, '2018-03-20 01:13:33', '2018-03-20 01:13:33');
